### Python programming documentation

#### 1 Definition:

Python is a high-level, interpreted programming language that allows people to write computer programs. Python is famous for its clear, simple syntax, making it suitable for beginners and professionals to build websites, analyze data, make games, control robots, and more.

### 2 Variables and data types

A variable is a named place in memory where you can store data like numbers, text, or lists. Python figures out what type of data you are storing (int, float, str, etc.) just from the value you assign it 

Variables help you remember and reuse information, like saving a user's name or a calculation result.

In [13]:
age = 18              
price = 19.99         
username = "Athahar"    
is_student = True     

we can check what dataype each variable is storing using type function

In [16]:
type(age)

int

In [18]:
type(price)

float

In [20]:
type(username)

str

In [22]:
type(is_student)

bool

### 3 Arithmetic Operators

### Definition:

Arithmetic operators are symbols that tell Python to perform math calculations like addition, subtraction, multiplication, division, and more.

They help you do calculations in your program, like adding numbers or finding results.

In [27]:
a = 10 + 5
b = 10 - 3
c = 4 * 3
d = 20 / 4
e = 7 % 3
f = 2 ** 3

In [60]:
print("Addition: a = 10 + 5 =", a)
print("Subtraction: b = 10 - 3 =", b)
print("Multiplication: c = 4 * 3 =", c)
print("Division: d = 20 / 4 =", d)
print("Modulus (remainder): e = 7 % 3 =", e)
print("Exponentiation: f = 2 ** 3 =", f)


Addition: a = 10 + 5 = 15
Subtraction: b = 10 - 3 = 7
Multiplication: c = 4 * 3 = 12
Division: d = 20 / 4 = 5.0
Modulus (remainder): e = 7 % 3 = 1
Exponentiation: f = 2 ** 3 = 8


### 4 Comparison Operators

### Definition: 

Comparison operators (like ==, <, >, !=, <=, >=) are used to compare two values. Python checks the relationship and returns True or False.

To decide what happens next in your code based on conditions.

In [35]:
age = 16
print(age < 18)  
print(age == 18)  

True
False


### 5. Logical Operators 

### Definition:

Logical operators (and, or, not) connect multiple conditions to check if multiple things are true or false.

It is used for more complex decisions, like checking several things at once.

In [42]:
x = 10
y = 20
print(x > 5 and y < 30)  
print(x < 5 or y < 15)    
print(not x == 10)       

True
False
False


### 6 Conditional Statements

### Definition:

Conditional statements help programs make choices. Python mainly uses three: if, elif, and else. Here's each part explained in detail:

### a) if Statement:

### Definition:
An if statement checks if a condition is True. If it is, the code inside the if block runs. If not, the block is skipped. It's the basic tool for decision-making in Python.

It is used have the code do something only if a certain test or condition is met.

In [47]:
number = 7
if number > 5:
    print("The number is bigger than 5.")

The number is bigger than 5.


### b) The elif Statement

### Definition:

elif is short for "else if". You use it to check a second (or third, or fourth, etc.) condition if the previous if condition(s) were False. It's a way to chain multiple choices together.

It is used when you have several possible options and you want to check them one by one.

In [50]:
marks = 80
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 60:
    print("Grade: C")

Grade: B


### c) The else Statement

### Definition

The else statement catches everything else that wasn't caught by the if or elif checks. You do not write a condition after else—it just runs if all the earlier tests fail.

It gives a default action or message when none of the above conditions are true.

In [53]:
score = 40
if score >= 90:
    print("Excellent!")
elif score >= 70:
    print("Good!")
else:
    print("Keep trying!")  

Keep trying!


Combining if, elif, and else:

In [58]:
temp = 15
if temp >= 30:
    print("It's hot outside")
elif temp >= 20:
    print("It's warm outside")
elif temp >= 10:
    print("It's cool outside")
else:
    print("It's cold outside")


It's cool outside


### 7. Loops

Loops repeat actions, saving you from writing the same code over and over. There are two main types: for and while.

### For Loop:

A for loop repeats code for each item in a list or range, one by one.

It is used to process every item in a group, or repeat an action a known number of times.

In [66]:
for i in range(1, 4):
    print(i)


1
2
3


### While Loop

### Definition:
A while loop repeats code as long as a condition remains True.

It is used to keep doing something until a certain point (possibly unknown in advance).

In [71]:
count = 0
while count < 3:
    print("Count is", count)
    count += 1

Count is 0
Count is 1
Count is 2


### 8 Object-Oriented Programming (OOPS)

### Definition:

Object-Oriented Programming (OOP) is a style of writing programs that brings code closer to the real world. In OOP, you design programs around objects—collections of data (attributes) and actions (methods) bundled together. This approach makes it easier to handle complex problems by grouping similar things and their behaviors.

OOP helps organize code, make programs easier to understand, and reuse code efficiently in large systems.

### a) Classes and Objects

### Class

#### Definition:

A class is like a blueprint or plan for making objects. It defines what data (attributes) and what actions (methods) objects of that kind will have.

To design various "types" of objects in your code, such as a Car, a Student, or a Book.

In [81]:
class Student:
    pass  

### Object

#### Definition:
An object is one specific thing created from a class blueprint. It can hold its own unique data.

Objects bring classes to life, turning a plan into something you can use and change.

In [84]:
obj = Student()

### b) Attributes and Method

##### Attributes Definition:
Attributes are pieces of information stored in an object—like a person's name or age.

To store important information about each object

In [87]:
class Car:
    def __init__(self, model):
        self.model = model

my_car = Car("Honda Civic")
print(my_car.model)

Honda Civic


#### Methods Definition:
Methods are functions that belong to a class. They describe what objects can do.

Methods help objects perform tasks or change their information.

In [94]:
class Cat:
    def sound(self):
        print("Meow")

pet = Cat()
pet.sound()   

Meow


### c) Inheritance
#### Definition:
Inheritance lets you create a new class (child) that automatically gets the features of another class (parent). You can also add new features or change existing ones in the child class.

To avoid repeating code and to create a clear relationship between objects.

In [101]:
class Vehicle:
    def move(self):
        print("Vehicle is moving")

class Bicycle(Vehicle):   # Bicycle inherits from Vehicle
    def move(self):
        print("Pedaling")

my_bike = Bicycle()
my_bike.move()   

Pedaling


### d) Encapsulation

#### Definition:

Encapsulation is wrapping the data (attributes) and the methods (actions) together into one class and hiding the inner details from outside the class.

To protect data and prevent it from being changed by accident.

In [105]:
class Account:
    def __init__(self, balance):
        self.__balance = balance  

    def deposit(self, amount):
        self.__balance += amount

    def get_balance(self):
        return self.__balance

my_acc = Account(100)
my_acc.deposit(50)
print(my_acc.get_balance())   

150


### e) Polymorphism

#### Definition:
Polymorphism means "many forms." In Python, it lets you use the same method name in different classes and the correct version will be used for each object.


To write flexible code that can work with objects of different types.

In [109]:
class Person:
    def __init__(self, name, age, profession):
        self.name = name
        self.age = age
        self.profession = profession

    def introduce(self):
        print(f"Hi, I'm {self.name}, {self.age} years old, and I work as a {self.profession}.")

    def celebrate_birthday(self):
        self.age += 1
        print(f"{self.name} just turned {self.age}!")


person1 = Person("Neha", 28, "Software Engineer")
person2 = Person("Raj", 34, "Doctor")

person1.introduce()      
person2.introduce()      
person1.celebrate_birthday()  


Hi, I'm Neha, 28 years old, and I work as a Software Engineer.
Hi, I'm Raj, 34 years old, and I work as a Doctor.
Neha just turned 29!


## Numpy and Pandas

## 1. What is NumPy?

NumPy (Numerical Python) is a powerful library in Python for working with numbers, especially arrays (tables of values). It provides incredibly fast ways to store, access, and do math on collections of numbers—much faster and more flexible than regular Python lists. NumPy forms the foundation for most scientific and data computing in Python.

**Uses**  
It makes handling big sets of numbers easy—like in statistics, engineering, or working with images. You can do calculations, reshaping, and complex mathematics all with just a few lines of code, and it's much faster than pure Python lists.


In [113]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## 2. NumPy Arrays

### a) Array Definition

A NumPy array is a grid or table of numbers, all stored together in memory. Unlike Python lists, NumPy arrays are typed (all numbers must be of the same type) and support fast mathematical operations.

**Uses**  
Arrays let you do things like adding, multiplying, or transforming entire groups of numbers instantly.


In [117]:
arr = np.array([10, 20, 30])
print(arr[1])  # Access second value: 20

20


### b)Creating Arrays

You can create arrays from Python lists, or generate special arrays (like zeros, ones, random numbers).

**Uses**  
To quickly build datasets and structures for computation.

In [125]:
zeros = np.zeros(3)         
ones = np.ones(5)           
rand = np.random.rand(4)   
print(zeros)
print(ones)
print(rand)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.48063187 0.21968775 0.32342814 0.34021448]


## c) Array Indexing and Slicing

Indexing lets you pick out specific numbers from an array. Slicing allows you to grab a part or chunk of an array.

**Uses**  
So you can examine, change, or analyze just certain rows or columns of data, like focusing on ages above 30.


In [130]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[:3])   

[10 20 30]


## 4. Array Operations

NumPy allows you to do math directly on arrays—like adding a number to every value, multiplying two arrays together, or running calculations across all elements.

**Uses**  
It massively speeds up calculations—imagine adding 5 to every number in a million-value array in one go!

In [135]:
arr = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
print(arr + arr2)        
print(arr * 2)           

[11 22 33]
[2 4 6]


## 5. Shape and Reshape

Shape describes how many rows and columns an array has. Reshape changes the layout into new dimensions (2D table, for example).

**Uses**  
To prepare data for analyses, convert between rows and columns, or organize for machine learning.

In [140]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))      
print(b)

[[1 2 3]
 [4 5 6]]


## 6. Aggregate Functions (Sum, Mean, Max, Min)

Aggregate functions allow you to quickly summarize data—like getting the total sum, average (mean), biggest (max), or smallest (min) value in your array.

**Uses**  
These let you instantly understand or analyze your data set in useful ways.

In [147]:
arr = np.array([3, 7, 5])
print(np.sum(arr))  
print(np.mean(arr)) 
print(np.max(arr))   
print(np.min(arr))   

15
5.0
7
3


## 7. Broadcasting

Broadcasting lets NumPy automatically extend smaller arrays so operations can be performed without writing loops. For example, adding a single value to every element of a big array.

**Uses**  
It saves time and code when working with arrays of different shapes.

arr = np.array([1, 2, 3])
arr = arr + 5     
print(arr)
arr = np.array([1, 2, 3])
arr = arr + 5     
print(arr)

## 8. Multidimensional Arrays (Matrices)

NumPy can handle 2D or more-dimensional arrays, making it perfect for working with tables (matrices), images, or higher-dimensional data.

**Uses**  
For scientific data, images, machine learning, and statistical tables.

In [157]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix[0, 1]) 

2


## 9. Saving and Loading Arrays

NumPy lets you save arrays to disk or load them again easily. This is useful when working with big data that you don’t want to recreate every time.

**Uses**  
For keeping and reusing work in long projects like analysis or machine learning.

In [168]:
arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)     
new_arr = np.load('my_array.npy')
print(new_arr)

[1 2 3]


## Pandas

## 1. What is pandas?

pandas is a Python library made for handling and analyzing data, usually in table form (think Excel sheets, CSV files, or SQL tables). It makes it easy to load, change, clean, and summarize big sets of data—with just a few commands.

**Uses**  
pandas turns messy or raw data into something easy to understand and analyze. It’s the go-to tool for data science, research, business analysis, and any work with rows and columns.

In [262]:
import pandas as pd
data = pd.DataFrame({'name': ['Athahar', 'Sai'], 'score': [88, 77]})
print(data)

      name  score
0  Athahar     88
1      Sai     77


## 2. DataFrame and Series

### a) DataFrame

A DataFrame is pandas’ main table object—like a supercharged Excel spreadsheet, with rows and columns you can easily change or extract from.

**Uses**  
It helps you organize, clean, and analyze data from the real world (contacts, sales, experiment results).


In [265]:
df = pd.DataFrame({'City': ['Hyderabad', 'Bangalore'], 'Population': [8, 4]})
print(df)

        City  Population
0  Hyderabad           8
1  Bangalore           4


### b) Series

A Series is like a single column from a DataFrame—a list with labels.

**Uses**  
For handling just one set of data (like ages) or working with column-by-column operations.

In [268]:
ages = pd.Series([23, 35, 29])
print(ages)

0    23
1    35
2    29
dtype: int64


## 3. Reading and Writing Data

### a) Reading CSV Files

You can load data from CSV or Excel files (spreadsheets) directly into pandas for analysis.

**Uses**  
To quickly load real-world data into your code.

In [271]:
df = pd.read_csv("churn.csv")
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0

### b) Writing to CSV Files

Saves your processed data back to CSV, so you can share or reuse it.

**Uses**  
For saving results, exporting cleaned data, or sharing findings.

In [274]:
df.to_csv('results.csv', index=False)

## 4. Selecting Data

You can easily select specific rows or columns using labels or numbers—just like in a spreadsheet.

**Uses**  
To focus on interesting or important parts of your data.

In [277]:
print(df['Age'])         
print(df.iloc[0])     
[['Age', 'Status']]

0       30
1       25
2       30
3       15
4       15
        ..
3145    25
3146    55
3147    30
3148    30
3149    30
Name: Age, Length: 3150, dtype: int64
Call  Failure                 8.00
Complains                     0.00
Subscription  Length         38.00
Charge  Amount                0.00
Seconds of Use             4370.00
Frequency of use             71.00
Frequency of SMS              5.00
Distinct Called Numbers      17.00
Age Group                     3.00
Tariff Plan                   1.00
Status                        1.00
Age                          30.00
Customer Value              197.64
Churn                         0.00
Name: 0, dtype: float64


[['Age', 'Status']]

## 5. Filtering Data

Filtering means picking out only the rows or values that meet certain conditions.

**Uses**  
Find important data, like high scores or locations above a certain population.

In [280]:
aged_people = df[df['Age'] > 35]
aged_people

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
20                7          0                    37               1   
23               21          1                    36               8   
30                3          0                    33               1   
31                0          1                    36               0   
32                0          0                    36               1   
...             ...        ...                   ...             ...   
3131              5          1                    38               0   
3132              5          0                    38               2   
3139              9          0                    28               1   
3141              5          0                    28               0   
3146             17          0                    17               1   

      Seconds of Use  Frequency of use  Frequency of SMS  \
20             11465               154                11   
23             10435                93                 1   
30              6785                97                14   
31               628                 7                 9   
32               338                 4                 4   
...              ...               ...               ...   
3131             933                13                16   
3132             643                10                11   
3139            1873                45                37   
3141            1130                16                28   
3146            9237               177                80   

      Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
20                         47          4            1       1   45   
23                         42          5            2       1   55   
30                         22          5            1       1   55   
31                          4          4            1       2   45   
32                          2          5            1       1   55   
...                       ...        ...          ...     ...  ...   
3131                        6          4            1       2   45   
3132                        4          5            1       1   55   
3139                       70          5            1       1   55   
3141                        5          4            1       2   45   
3146                       42          5            1       1   55   

      Customer Value  Churn  
20           317.975      0  
23           159.420      0  
30           124.230      0  
31            38.375      1  
32            11.130      0  
...              ...    ...  
3131          63.650      1  
3132          26.295      0  
3139          84.270      0  
3141          98.650      0  
3146         261.210      0  

[565 rows x 14 columns]

## 6. Adding and Removing Columns

pandas lets you create new columns (from calculations) or remove columns you don’t need.

**Uses**  
To tidy up or add useful metrics to your dataset.

In [283]:
df["new_customer_value"] = df["Customer Value"]/2
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  new_customer_value  
0         197.640      0             98.8200  
1          46.035      0             23.0175  
2        1536.520      0            768.2600  
3         240.020      0            120.0100  
4         145.805      0             72.9025

In [285]:
del df["new_customer_value"]
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0

## 7. Handling Missing Data

Real data often has missing values. pandas can find and fill (or drop) these empty spots easily.

**Uses**  
To clean data for analysis or machine learning.

In [288]:
df_with_nan = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
print(df_with_nan.fillna(0)) 
print(df_with_nan.dropna())   

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0
     A    B
0  1.0  4.0


## 8. Grouping and Aggregation

Grouping clusters your data by some value (like city or month), letting you calculate summaries for each group.

**Uses**  
To summarize, compare, or analyze trends by category.

In [291]:
scores = pd.DataFrame({'Team': ['A', 'B', 'A'], 'Points': [10, 20, 30]})
team_totals = scores.groupby('Team')['Points'].sum()
print(team_totals)

Team
A    40
B    20
Name: Points, dtype: int64


## 9. Sorting Data

pandas can arrange your table by values in any column, alphabetically or by size.

**Uses**  
To see the biggest, smallest, or otherwise organize your dataset.

In [294]:
df_sorted = df.sort_values('Seconds of Use', ascending=False)
df_sorted.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
2983             36          0                    34               5   
2583             34          0                    33               6   
883              31          1                    32               4   
483              29          0                    31               5   
2383             35          0                    39               5   

      Seconds of Use  Frequency of use  Frequency of SMS  \
2983           17090               255                15   
2583           16980               254                28   
883            16785               249                 8   
483            16675               248                21   
2383           16640               254                22   

      Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
2983                       82          2            2       1   25   
2583                       97          2            2       1   25   
883                        80          2            1       1   25   
483                        95          2            1       1   25   
2383                       88          2            2       1   25   

      Customer Value  Churn  
2983         848.025      0  
2583         901.530      0  
883          802.530      0  
483          856.035      0  
2383         859.230      0

## 10. Merging and Joining DataFrames

You can combine two tables using a common column—just like matching student names to their grades.

**Uses**  
To combine more information from different sources, build larger analysis, or bring together related datasets.

In [297]:
data1 = pd.DataFrame({'ID': [1,2], 'Name': ['Anna', 'Bob']})
data2 = pd.DataFrame({'ID': [1,2], 'Score': [95, 88]})
merged = pd.merge(data1, data2, on='ID')
print(merged)

   ID  Name  Score
0   1  Anna     95
1   2   Bob     88


## 11. Applying Functions

pandas allows you to apply a function to every item or row in a column, making quick transformations or calculations.

**Uses**  
To process data flexibly, like formatting names or doing calculations.

In [300]:
df['Seconds of Use'] = df['Seconds of Use'].apply(lambda x: x / 1000000)
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0        0.004370                71                 5   
1        0.000318                 5                 7   
2        0.002453                60               359   
3        0.004198                66                 1   
4        0.002393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0